### ISSUE TITLE
NameError: name 'messageID' is not defined

### ISSUE THREAD

**Issue by billyjbryant** [rx13/dc29-discord-signalbot#1]
By default, you get this error: 

```
✦ ❯ python3 main.py
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    dc29SignalChatReact = f'{dc29SignalChat}/{messageID}/reactions/%F0%9F%91%8D/%40me'
NameError: name 'messageID' is not defined
```

**Comment by rx13** [comment]
Check your version, I believe that was an issue on Saturday, but should've since been updated.

**Comment by rx13** [comment]
I cannot find a commit history with that specific version in it, but the format string prefix `f` is the issue there. It shouldn't be.

We call format on it later when it gets used for replies.
` dc29SignalChatReact = '{dc29SignalChat}/{messageID}/reactions/%F0%9F%91%8D/%40me'`
